# Generated by Django 4.0.1 on 2022-03-02 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Nome dell'articolo")),
                ('measurement_unit', models.CharField(default='', max_length=50, verbose_name='Unità di misura')),
            ],
            options={
                'verbose_name': 'article',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome del cliente')),
            ],
            options={
                'verbose_name': 'client',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Setting',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome del fornitore')),
            ],
            options={
                'verbose_name': 'supplier',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome del cantiere')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagementSoftware.client', verbose_name='Nome del cliente')),
            ],
            options={
                'verbose_name': 'site',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('installed', 'Installato'), ('delivered', 'Consegnato'), ('in-stock', 'In Giacenza'), ('ordered', 'Ordinato'), ('withdraw', 'Da Ritirare'), ('to-confirm', 'In Attesa'), ('to-order', 'Da Ordinare')], max_length=50, verbose_name='Stato dell ordine')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantità dell ordine')),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagementSoftware.article', verbose_name='Nome dell articolo')),
                ('clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagementSoftware.client', verbose_name='Nome dell Clienti')),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagementSoftware.site', verbose_name='Nome del cantiere')),
                ('suppliers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagementSoftware.supplier', verbose_name='Nome dell Fornitori')),
            ],
            options={
                'verbose_name': 'order',
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='article',
            name='supplier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagementSoftware.supplier', verbose_name='Nome del fornitore'),
        ),
    ]
